spring.application.name=EasyChat

# ===============================
# SERVER
# ===============================
server.port=${PORT}
server.servlet.context-path=/easychat
spring.main.lazy-initialization=true

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}

# ===============================
# Mailjet Configuration
# ===============================
mailjet.api-key=${MAILJET_API_KEY}
mailjet.secret-key=${MAILJET_SECRET_KEY}

# ===============================
# APP CONFIG
# ===============================
app.base-url=${APP_BASE_URL}


